#!/bin/bash
if [[ $PANDOC_IMG ]] && [[ $DOCNAME ]] && [[ $DOCTEMPLATE ]];then

  docker run  -v `pwd`:/data -v `pwd`/../Assets:/Assets -v `pwd`/../Assets:/assets $PANDOC_IMG -t latex --pdf-engine=tectonic --from markdown --listings -V linkcolor:blue --template=${DOCTEMPLATE} --output ${DOCNAME}.pdf "${DOCNAME}.md"

elif [[ $PANDOC_IMG ]] && [[ $DOCNAME ]];then

  docker run  -v `pwd`:/data -v `pwd`/../Assets:/Assets -v `pwd`/../Assets:/assets $PANDOC_IMG -t latex --pdf-engine=tectonic --from markdown --listings -V linkcolor:blue --output ${DOCNAME}.pdf "${DOCNAME}.md"

fi
